name: ReduceSneakDamage
main: com.zach_attack.rsd.Main
version: 1.6
api-version: 1.14
website: https://www.spigotmc.org/resources/serverinfo.61518/
description: Reduces a players damage when sneaking.
commands:
  reducesneakdmg:
    description: Displays basic plugin info for ReducedSneakDmg
    aliases: [rsd, reducesneakdamage]
permissions:
  reducesneakdmg.use:
     description: Players with this permission will take less damage.
     default: true
  reducesneakdmg.admin:
     description: Players with this permission can reload the plugin.
     default: false
